version: '3'

services:
  ussd_decoder:
    image: ussd-decoder
    restart: unless-stopped
    container_name: ussd-decoder
    build:
      context: ./
    environment:
      - DB_URL=jdbc:postgresql://psql:5432/ussd_decoder
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:8081"

networks:
  default:
    external:
      name: local