version: '3'

services:
  ussd_decoder:
    image: alexyekymov/ussd-decoder:1.0.0
    restart: unless-stopped
    container_name: ussd-decoder
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_USERNAME=$${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=$${DB_PASSWORD}
    networks:
      - local
    ports:
      - "8081:8081"

networks:
  local:
    external: true
